import type { Dish, DishCategory } from '@/types/dishes';

// Helper to map old categoryIds to new DishCategory
function mapToCategory(categoryId: string): DishCategory {
  const map: Record<string, DishCategory> = {
    'cat-principales': 'minutas',
    'cat-entradas': 'entradas',
    'cat-guarniciones': 'entradas',
  };
  return map[categoryId] || 'minutas';
}

export function buildInitialDishes(): Dish[] {
  const now = new Date();
  return [
  {
    id: 'dish-hamburguesa',
    name: 'Hamburguesa clásica',
    category: 'hamburguesas',
    price: 3500,
    recipe: [
      { ingredientId: 'ing-pan-hamburguesa', ingredientName: 'Pan de hamburguesa', quantity: 1, unit: 'unidades', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-carne-picada', ingredientName: 'Carne picada', quantity: 0.2, unit: 'kg', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-queso-cheddar', ingredientName: 'Queso cheddar', quantity: 0.05, unit: 'kg', isOptional: true, isRemovable: true },
      { ingredientId: 'ing-lechuga', ingredientName: 'Lechuga', quantity: 0.25, unit: 'unidades', isOptional: true, isRemovable: true },
      { ingredientId: 'ing-tomate', ingredientName: 'Tomate', quantity: 0.1, unit: 'kg', isOptional: true, isRemovable: true },
    ],
    customizationOptions: [],
    maxAvailable: 0,
    isAvailable: true,
    description: 'Hamburguesa de carne con queso, lechuga y tomate',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'dish-milanesa-napolitana',
    name: 'Milanesa napolitana',
    category: 'minutas',
    price: 4200,
    recipe: [
      { ingredientId: 'ing-nalga', ingredientName: 'Nalga', quantity: 0.3, unit: 'kg', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-huevos', ingredientName: 'Huevos', quantity: 2, unit: 'unidades', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-pan-rallado', ingredientName: 'Pan rallado', quantity: 0.1, unit: 'kg', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-pure-tomate', ingredientName: 'Puré de tomate', quantity: 1, unit: 'unidades', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-queso-mozzarella', ingredientName: 'Queso mozzarella', quantity: 0.1, unit: 'kg', isOptional: true, isRemovable: true },
      { ingredientId: 'ing-oregano', ingredientName: 'Orégano', quantity: 0.01, unit: 'kg', isOptional: true, isRemovable: true },
    ],
    customizationOptions: [],
    maxAvailable: 0,
    isAvailable: true,
    description: 'Milanesa napolitana con jamón, queso y salsa de tomate',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'dish-ensalada-mixta',
    name: 'Ensalada mixta',
    category: 'ensaladas',
    price: 1800,
    recipe: [
      { ingredientId: 'ing-lechuga', ingredientName: 'Lechuga', quantity: 1, unit: 'unidades', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-tomate', ingredientName: 'Tomate', quantity: 0.2, unit: 'kg', isOptional: true, isRemovable: true },
      { ingredientId: 'ing-cebolla', ingredientName: 'Cebolla', quantity: 0.1, unit: 'kg', isOptional: true, isRemovable: true },
      { ingredientId: 'ing-aceite-oliva', ingredientName: 'Aceite de oliva', quantity: 0.05, unit: 'litros', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-vinagre', ingredientName: 'Vinagre', quantity: 0.02, unit: 'litros', isOptional: true, isRemovable: true },
    ],
    customizationOptions: [],
    maxAvailable: 0,
    isAvailable: true,
    description: 'Ensalada fresca con lechuga, tomate, cebolla y aderezo',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'dish-omelette-jamon-queso',
    name: 'Omelette de jamón y queso',
    category: 'entradas',
    price: 2200,
    recipe: [
      { ingredientId: 'ing-huevos', ingredientName: 'Huevos', quantity: 3, unit: 'unidades', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-jamon-cocido', ingredientName: 'Jamón cocido', quantity: 0.1, unit: 'kg', isOptional: true, isRemovable: true },
      { ingredientId: 'ing-queso-cremoso', ingredientName: 'Queso cremoso', quantity: 0.1, unit: 'kg', isOptional: true, isRemovable: true },
      { ingredientId: 'ing-manteca', ingredientName: 'Manteca', quantity: 0.02, unit: 'kg', isOptional: false, isRemovable: false },
    ],
    customizationOptions: [],
    maxAvailable: 0,
    isAvailable: true,
    description: 'Omelette relleno de jamón cocido y queso cremoso',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'dish-pizza-mozzarella',
    name: 'Pizza mozzarella',
    category: 'pizzas',
    price: 3800,
    recipe: [
      { ingredientId: 'ing-harina-000', ingredientName: 'Harina 000', quantity: 0.5, unit: 'kg', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-levadura', ingredientName: 'Levadura', quantity: 1, unit: 'unidades', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-aceite-girasol', ingredientName: 'Aceite de girasol', quantity: 0.1, unit: 'litros', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-tomate-triturado', ingredientName: 'Tomate triturado', quantity: 1, unit: 'unidades', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-queso-mozzarella', ingredientName: 'Queso mozzarella', quantity: 0.3, unit: 'kg', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-oregano', ingredientName: 'Orégano', quantity: 0.01, unit: 'kg', isOptional: true, isRemovable: true },
    ],
    customizationOptions: [],
    maxAvailable: 0,
    isAvailable: true,
    description: 'Pizza de mozzarella clásica con salsa de tomate',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'dish-papas-fritas',
    name: 'Papas fritas',
    category: 'entradas',
    price: 1500,
    recipe: [
      { ingredientId: 'ing-papa', ingredientName: 'Papa', quantity: 0.4, unit: 'kg', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-aceite-girasol', ingredientName: 'Aceite de girasol', quantity: 0.2, unit: 'litros', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-sal', ingredientName: 'Sal', quantity: 0.01, unit: 'kg', isOptional: false, isRemovable: false },
    ],
    customizationOptions: [],
    maxAvailable: 0,
    isAvailable: true,
    description: 'Papas fritas crujientes',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'dish-pancho-completo',
    name: 'Pancho completo',
    category: 'sandwiches',
    price: 2800,
    recipe: [
      { ingredientId: 'ing-pan-pancho', ingredientName: 'Pan de pancho', quantity: 1, unit: 'unidades', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-salchichas', ingredientName: 'Salchichas', quantity: 1, unit: 'unidades', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-salsa-golf', ingredientName: 'Salsa golf', quantity: 0.05, unit: 'kg', isOptional: true, isRemovable: true },
      { ingredientId: 'ing-mostaza', ingredientName: 'Mostaza', quantity: 0.03, unit: 'kg', isOptional: true, isRemovable: true },
      { ingredientId: 'ing-choclo-lata', ingredientName: 'Choclo en lata', quantity: 0.5, unit: 'unidades', isOptional: true, isRemovable: true },
    ],
    customizationOptions: [],
    maxAvailable: 0,
    isAvailable: true,
    description: 'Pancho completo con salsa golf, mostaza y choclo',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'dish-tarta-verduras',
    name: 'Tarta de verduras',
    category: 'minutas',
    price: 3200,
    recipe: [
      { ingredientId: 'ing-tapas-empanadas', ingredientName: 'Tapas para empanadas', quantity: 2, unit: 'unidades', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-cebolla', ingredientName: 'Cebolla', quantity: 0.2, unit: 'kg', isOptional: false, isRemovable: false },
      { ingredientId: 'ing-zapallito', ingredientName: 'Zapallito', quantity: 2, unit: 'unidades', isOptional: true, isRemovable: true },
      { ingredientId: 'ing-morron-rojo', ingredientName: 'Morrón rojo', quantity: 1, unit: 'unidades', isOptional: true, isRemovable: true },
      { ingredientId: 'ing-queso-cremoso', ingredientName: 'Queso cremoso', quantity: 0.2, unit: 'kg', isOptional: true, isRemovable: true },
      { ingredientId: 'ing-huevos', ingredientName: 'Huevos', quantity: 2, unit: 'unidades', isOptional: false, isRemovable: false },
    ],
    customizationOptions: [],
    maxAvailable: 0,
    isAvailable: true,
    description: 'Tarta de verduras con cebolla, zapallito y morrón',
    createdAt: now,
    updatedAt: now,
  },
  ];
}
